include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

stages:
  - lint
  - test

gdscriptlint:
  image: python:3
  stage: lint
  before_script:
    - pip3 install git+https://github.com/Scony/godot-gdscript-toolkit.git
  script:
    - gdlint .

markdownlint:
  image: node:latest
  stage: lint
  before_script:
    - npm install
  script:
    - npm run markdownlint
    - npm run changeloglint

sast:
  stage: test
